Added pull_request_template and issue_template
codeisscience/journal-policy-tracker-backend pull request #40
Opened 2021-10-29 16:03 UTC by HarshalRathore

Solves #7 
I request @CIPHERTron / @yochannah  to review my PR and if no further changes are required then please merge these changes or add `hacktoberfest-accepted` label to this PR before 31st Oct as it will be counted towards my 4PR count.
Thank you.
Signed-off-by: HarshalRathore <harshalrathore2014@gmail.com>

2021-10-30 13:34 UTC, CIPHERTron requested changes
Heyy @HarshalRathore, first of all, thanks for your contributions.
Second, the PR template looks good but the issue template that you've added here is outdated.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

You can take a look here ⬆️ 
This is the updated version of the issue templates that people tend to use nowadays 🙂

2021-11-03 17:46 UTC, HarshalRathore commented
Hii @CIPHERTron
First thanks for adding `hactoberfest-accepted` label even before I submitted the requested changes.
So I checked out the new Issue forms I wanted to ask that do you only want me to create a single issue form template like only for `Bug-report` which is what I originally submitted or do you also want me to create a separate template for when people want to submit a `new-idea` or propose enhancement.
BTW this PR is showing under review for next 12 days so I think hactoberfest will count it only after the review period is over. Do you know something about this.

2021-11-03 19:50 UTC, HarshalRathore commented
Hii @CIPHERTron 
I have added an Issue form template for `Report-a-bug` as you asked. please review it.
To see how this form actually looks like in action see [here](https://github.com/HarshalRathore/Hello-World/issues/new?assignees=&labels=bug%2Ctriage&template=report-a-bug.yml&title=%5BBug%5D%3A+)
I created a testing repository to test this issue form there it's [Hello-World](https://github.com/HarshalRathore/Hello-World) you can see this issue form there, try to file a bug issue there.

2022-01-30 17:03 UTC, JPTIZ commented on .github/PULL_REQUEST_TEMPLATE.md
> +* SDK:
I think these aren't relevant for our case, as we rely on Python installation with no AOT compiler toolchain needed. I would rather, if wanted, add Python/tooling versions:

```suggestion
**Test Configuration**:

* Python version:
* Poetry version:
```

2022-01-30 17:07 UTC, JPTIZ commented on .github/ISSUE_TEMPLATE/report-a-bug.yml
> +        Example: "This is the expected behaviour from it."
What do you think about rewording like this?

```suggestion
        Example: "It was expected that <X> happened."
        Or "Data returned should be in format <Y>."
```

2022-01-30 17:08 UTC, JPTIZ commented on .github/ISSUE_TEMPLATE/report-a-bug.yml
> +      description: If you are reporting a console error, please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks..
Oh wow :exploding_head: This issue submission by form is mind-blowing haha

2022-01-30 17:09 UTC, JPTIZ commented
I think that's it for me, if @CIPHERTron doesn't have something else to add, after fixing them I consider it approved.

2022-01-30 20:02 UTC, JPTIZ approved these changes
I'll wait for a second approval :)

2022-01-31 06:13 UTC, CIPHERTron reviewed
@HarshalRathore thanks for the PR. Overall LGTM 🚀 
Just a couple of suggestions and then I can approve this PR

2022-01-31 06:13 UTC, CIPHERTron commented on .github/ISSUE_TEMPLATE/report-a-bug.yml
> +        - label: I have readed the [Contributing Guidelines](https://github.com/codeisscience/journal-policy-tracker-backend/blob/master/CONTRIBUTING.md).
a small typo: **read**

2022-01-31 06:13 UTC, CIPHERTron commented on .github/ISSUE_TEMPLATE/report-a-bug.yml
> +        - label: I am running the latest version.
how about removing this label as of now?

2022-01-31 14:35 UTC, CIPHERTron approved these changes
LGTM 🎉

2022-01-31 14:37 UTC, merged

2022-01-31 14:37 UTC, JPTIZ commented
2 approvals, way to go :) Thank you for your contribution and @CIPHERTron for the proper and ready review!

2022-01-31 14:43 UTC, HarshalRathore commented
Thank you @JPTIZ and @CIPHERTron. I was able to learn something new from this.

2022-01-31 15:21 UTC, CIPHERTron commented
> Thank you @JPTIZ and @CIPHERTron. I was able to learn something new from this.

Thank you for your contributions ❤️ 

If you're interested in full-stack development do check out the repositories in [code-is-science](https://github.com/codeisscience) organization. Do let me know if I can help you anyway and don't forget to join our slack 
 where all the conversations take place 😃  

You can find the slack invite [here](https://codeisscience-community.netlify.app/)