Fix for database tables not being created in Heroku
codeisscience/journal-policy-tracker-backend pull request #46
Opened 2022-03-31 04:12 UTC by erik-whiting

# Description
## Database Tables not Being Created
In the `codecompl.py` file, I added import statements that import all of the models in the `server/models` directory. With those models in the namespace, we can then call `db.create_all()` and `db.session.commit()` which will create the database tables. These functions don't wipe out any data locally; as long as there are database files (the ones ending with `.db`) the data still persists.

## Deploying to Heroku
In order to deploy this to my own Heroku instance, I had to use Pipfile. This is because that's how Heroku determines that the application needs a Python-friendly environment so to speak. Alternatively, I could've used `requirements.txt` but after doing some reading it looks like Heroku prefers the Pipfile approach.

Note, if you can already deploy this app to your own Heroku instance without the changes I made, then I will remove that work from this PR. I separated the Heroku work and the database table work into two different commits, so if my Pipfile changes aren't wanted, I can easily roll them back before merging.

## Important! SQLite database will not persist on Heroku
I tested this to make sure my approach with the database tables doesn't wipe out existing data when the server is reset. Locally, it doesn't. However, it seems that it does with Heroku but that's because the database is SQLite. According to [this article](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem) from Heroku themselves:
>If you were to use SQLite on Heroku, you would lose your entire database at least once every 24 hours.

So if you want your database to persist, you will probably have to start using MySQL or Postgres or something similar. If that's something you'd like to do, please let me know if you'd like me to get started on the work to make that possible.

At least this has been my experience with deploying to Heroku. If you've already done some magic to make sure that `.db` files persist indefinitely, then the changes in this PR will not affect that.

Fixes #42 
 
## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
## Local Test - No Database
1. Make code changes
2. Go to journals page, see that there is no error
3. Use postman to create a new journal record
4. Go to journals page, see that there is no error and that the record I created exists

## Local Test - Existing Database
1. After completing "*Local Test - No Database*", stop the server
2. Restart the server
3. Go to journals page, see that there is no error and that the record still exists

## Local Test - Do it All Over
1. I deleted the database files
2. Repeated both test cases as above
3. Saw that everything still works as expected

## Heroku Test
I repeated the first two tests against a Heroku instance. With my fixes, the database tables are created and you can read and write to them. However, the database will be wiped out on new deploys as well as at least once every 24 hours. This is _**not because of any code changes**_ but because Heroku uses an [ephemeral filesystem](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem) and according to [their own documentation](https://devcenter.heroku.com/articles/sqlite3#disk-backed-storage), SQLite databases won't persist indefinitely on their servers.

**Test Configuration**:

* Python version: 3.9.4
* Poetry version: 1.1.13

# Checklist:

- [X] I have readed the [Contributing Guidelines](https://github.com/codeisscience/journal-policy-tracker-backend/blob/master/CONTRIBUTING.md).

- [X] My behaviour/Contribution abides by the [Code of Conduct](https://github.com/codeisscience/journal-policy-tracker-backend/blob/master/CODE_OF_CONDUCT.md).

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- _**N/A**_
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- I manually tested my changes but there are no existing tests in this repository so I wouldn't know where to put them
- [ ] New and existing unit tests pass locally with my changes
- _**N/A**_

2022-04-08 01:22 UTC, JPTIZ requested changes
Since we already use [Poetry](https://python-poetry.org/) (see this repo's [pyproject.toml](https://github.com/codeisscience/journal-policy-tracker-backend/blob/master/pyproject.toml)), I wouldn't add Pipenv files unless, for some reason, it is strictly necessary.

About the changes, as much as I tested (first from your branch after deleting journals.db, then  from master deleting journals.db beforehand as well) it works :) So removing the Pipenv files and addressing my other comment should be enough for approval.

(Oh, and thank you for fixing this!)

2022-04-08 01:23 UTC, JPTIZ commented on codecompl.py
> +from server.models import *
```suggestion
```

2022-04-08 01:52 UTC, erik-whiting commented
Hey @JPTIZ , thanks so much for the feedback.

I wanted to mention one thing regarding the use of `*` vs explicitly importing classes. This `import` statement is the part that builds the tables upon deployment. Say we add a new table called `Foo`; we wouldn't have to make any changes to this file in order to build the `Foo` table upon deployment (provided we define the class in the right place). With explicit importation, we'll have to come back to this file any time we add a table to the database (e.g., `from db.models import User, Journal` would have to become `from db.models import User, Journal, Foo`).

I'll definitely make the requested changes, just be advised that when a new table is added, it'll have to be explicitly imported in this file as well.

Regarding using poetry to deploy, I could not get my own Heroku instance of this application to deploy correctly without using a pipfile. I'll go ahead and remove that in this PR, but I won't be able to test it on my own instance, you may have to double check everything deploys ok yourself 😬 

I'll tag you again once the changes are made, thanks again so much for getting back to me!

2022-04-09 05:42 UTC, erik-whiting commented
@JPTIZ thanks again for your feedback yesterday, I've made the requested changes. Let me know if I can help with anything else :)

2022-04-09 15:08 UTC, JPTIZ approved these changes

2022-04-09 15:09 UTC, merged