feat(user-auth): add changeUsername Mutation
codeisscience/journal-policy-tracker-backend pull request #82
Opened 2022-11-25 06:36 UTC by khanjasir90

Signed-off-by: khanjasir90 <khanmohdjasir@gmail.com
Description: Added mutation for changeUsername

2022-11-25 06:45 UTC, khanjasir90 commented
https://www.loom.com/share/8596b9f6453a4661b6ecd1a13dfe9b66

2022-11-25 08:19 UTC, d-e-v-esh requested changes
This is good. Just few small corrections and it'll be good to go 👍

2022-11-25 08:19 UTC, d-e-v-esh commented on src/resolvers/userResolver.js
> +      const { oldUsername, newUsername } = userInfo;
I do not think we need to extract the `oldUsername` from the `userInfo`. That would require the user to enter their current username by themselves. We can extract the `oldUsername` from the `req` context. Check `getCurrentUser` query to see how that can be done.

2022-11-25 08:19 UTC, d-e-v-esh commented on src/resolvers/userResolver.js
> +              message: "Old and New Username are same",
I think we should keep all the error messages in lowercase.

2022-11-25 10:10 UTC, d-e-v-esh commented
Did you run this updated code?

2022-11-25 12:59 UTC, khanjasir90 commented
actually there are still some changes that are needed to be made and by mistake I have made a commit! I'll do that and commit again.

2022-11-29 05:40 UTC, khanjasir90 commented
@d-e-v-esh I have made the necessary changes and it's working on my end too.

2022-11-29 06:16 UTC, d-e-v-esh commented
You're on the right track. But I think you are getting confused about how to use the id from `req`. I wrote a little bit about it in my GSoC blog. Take a look at it. Maybe it can help. 👍
https://gist.github.com/d-e-v-esh/cd150019b3bb1188e13eb0df9b210ef9#difference-between-_id-and-id

2022-11-29 07:27 UTC, khanjasir90 commented
> You're on the right track. But I think you are getting confused about how to use the id from `req`. I wrote a little bit about it in my GSoC blog. Take a look at it. Maybe it can help. 👍 https://gist.github.com/d-e-v-esh/cd150019b3bb1188e13eb0df9b210ef9#difference-between-_id-and-id

@d-e-v-esh thanks for the resource! it really helped me :) and I have also made the necessary changes. Thank you

2022-11-30 09:02 UTC, d-e-v-esh commented
Yes, I think it looks good. Can you please clean up all the commits and put them into a single commit. Also clean up the console log and unused import, then we can merge it 👍

2022-11-30 13:07 UTC, d-e-v-esh requested changes

2022-11-30 13:07 UTC, d-e-v-esh commented on src/resolvers/userResolver.js
> +                message: "username already exist's",
`username already exists`

2022-11-30 13:07 UTC, d-e-v-esh commented on src/resolvers/userResolver.js
> +              message: "username does'nt exist's",
`username does not exist`

2022-11-30 18:05 UTC, khanjasir90 commented
@d-e-v-esh yes would do the needful changes and will make a final commit!

2022-12-02 06:44 UTC, closed without merging