feat(user-auth): add changePassword mutation
codeisscience/journal-policy-tracker-backend pull request #87
Opened 2022-12-10 15:02 UTC by khanjasir90

Signed-off-by: khanjasir90 <khanmohdjasir@gmail.com>
Description: added changePassword Mutation

2022-12-10 15:03 UTC, khanjasir90 commented
@d-e-v-esh could u pls review it

2022-12-10 16:23 UTC, d-e-v-esh requested changes
The code looks really good 💯. Just a couple of things that we need to change.

2022-12-10 16:23 UTC, d-e-v-esh commented on src/resolvers/userResolver.js
> +      const isOldPassword = await bcrypt.compare(oldPassword, password);
The variable `isOldPassword` can be more descriptive so it is easier to read. You might write it as `isOldPasswordCorrect` or something like it.

2022-12-10 16:23 UTC, d-e-v-esh commented on src/resolvers/userResolver.js
> +      if(oldPassword === newPassword) {
I don't think we need to give them an error if both passwords are the same so we can remove this check.

2022-12-11 04:19 UTC, khanjasir90 commented
@d-e-v-esh I have made the required changes!

2022-12-11 07:51 UTC, d-e-v-esh commented
The code works well, clean up the extra commit and I'll merge. 👍

2022-12-11 14:53 UTC, merged